#spring.application.name=Food_Donation
#
#server.port=8080
## Database
#spring.datasource.url=jdbc:mysql://localhost:3306/food_donation
#spring.datasource.username=root
#spring.datasource.password=root123
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
## JWT
#app.jwt.secret=${APP_JWT_SECRET:foodDonationSuperSecretKeyForJwtTokenGeneration2026}
#app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}


 #new::
spring.application.name=Food_Donation

# Dynamic port
server.port=${PORT:8080}

# ================= DATABASE =================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/food_donation}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ================= JWT =================
app.jwt.secret=${APP_JWT_SECRET:foodDonationSuperSecretKeyForJwtTokenGeneration2026}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}